### ISSUE TITLE
Clover problem here

### ISSUE THREAD

**Issue by punyawatsu** [Am1nCmd/Dell-Inspiron-14-7447-Pandora-Hackintosh#10]
I use high sierra and update to mojave or Catalina It works well and can boot on first boot after I shutdown and start again clover can't see os(apfs) i think it might be APFS not detect in clover Please help

**Comment by Am1nCmd** [comment]
thats your problem with clover, I'm just provide an EFI files

I'm using clover v5058 when release this EFI
