### ISSUE TITLE
Sleep instantly wakes up 

### ISSUE THREAD

**Issue by Tcloser** [Am1nCmd/Dell-Inspiron-14-7447-Pandora-Hackintosh#11]
HI!
Your work is particularly useful to me, but I can't sleep when running on mac10.14.6。
Is there any solution？

command:
`log show --style syslog | fgrep "Wake reason"`
Following:
`2020-03-23 19:13:09.777510+0800  localhost kernel[0]: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: HDEF XHC`
`2020-03-23 19:13:09.777513+0800  localhost kernel[0]: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: HDEF XHC`

Thank u !

**Comment by ikarr** [comment]
Hey! I have the problem too, because plug in a USB device. I use 'Hackintool' change the usb type to Internal, can fix the problem. My english is not good, i don't know if i can understand.

**Comment by ikarr** [comment]
> 嗨！
> 您的工作对我特别有用，但是在mac10.14.6上运行时我无法入睡。
> 有什么解决方案吗？
> 
> 命令：
> `log show --style syslog | fgrep "Wake reason"`
> 以下：
> `2020-03-23 19:13:09.777510+0800 localhost kernel[0]: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: HDEF XHC`
> `2020-03-23 19:13:09.777513+0800 localhost kernel[0]: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: HDEF XHC`
> 
> 感谢你 ！



> 嗨！
> 您的工作对我特别有用，但是在mac10.14.6上运行时我无法入睡。
> 有什么解决方案吗？
> 
> 命令：
> `log show --style syslog | fgrep "Wake reason"`
> 以下：
> `2020-03-23 19:13:09.777510+0800 localhost kernel[0]: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: HDEF XHC`
> `2020-03-23 19:13:09.777513+0800 localhost kernel[0]: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: HDEF XHC`
> 
> 感谢你 ！

Hey! I have the problem too, because plug in a USB device. I use 'Hackintool' change the usb type to Internal, can fix the problem. My english is not good, i don't know if i can understand.

**Comment by ikarr** [comment]
> HI!
> Your work is particularly useful to me, but I can't sleep when running on mac10.14.6。
> Is there any solution？
> 
> command:
> `log show --style syslog | fgrep "Wake reason"`
> Following:
> `2020-03-23 19:13:09.777510+0800 localhost kernel[0]: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: HDEF XHC`
> `2020-03-23 19:13:09.777513+0800 localhost kernel[0]: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: HDEF XHC`
> 
> Thank u !

Hey! I have the problem too, because plug in a USB device. I use 'Hackintool' change the usb type to Internal, can fix the problem. My english is not good, i don't know if you can understand.

**Comment by Tcloser** [comment]
> > HI!
> > Your work is particularly useful to me, but I can't sleep when running on mac10.14.6。
> > Is there any solution？
> > command:
> > `log show --style syslog | fgrep "Wake reason"`
> > Following:
> > `2020-03-23 19:13:09.777510+0800 localhost kernel[0]: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: HDEF XHC`
> > `2020-03-23 19:13:09.777513+0800 localhost kernel[0]: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: HDEF XHC`
> > Thank u !
> 
> Hey! I have the problem too, because plug in a USB device. I use 'Hackintool' change the usb type to Internal, can fix the problem. My english is not good, i don't know if you can understand.

Thank you very much , I will have a try now.
另外说英语要自信hh

**Comment by Tcloser** [comment]
WOW, it's wonderful!!

**Comment by ikarr** [comment]
> WOW, it's wonderful!!

我也有一个问题，就是开机的时候会有一个开机的声音，请问你有没有这个情况？能否把声音取消呢，声音确实挺大的。

**Comment by Tcloser** [comment]
> > WOW, it's wonderful!!
> 
> 
> 
> 我也有一个问题，就是开机的时候会有一个开机的声音，请问你有没有这个情况？能否把声音取消呢，声音确实挺大的。

哈哈哈 dang～ 试过了好多办法去不了

**Comment by Tcloser** [comment]
> > WOW, it's wonderful!!
> 
> 
> 
> 我也有一个问题，就是开机的时候会有一个开机的声音，请问你有没有这个情况？能否把声音取消呢，声音确实挺大的。

还有它睡眠会到一定时间自己醒吗？好像一个小时左右鼠标亮了😂

**Comment by ikarr** [comment]
哎，我已经不想折腾了。今天安装个office，然后系统就卡死了，之前我用磁盘工具创建镜像，也卡死一次。我已经想回Windows10了。

**Comment by ikarr** [comment]
> > > WOW, it's wonderful!!
> > 
> > 
> > 我也有一个问题，就是开机的时候会有一个开机的声音，请问你有没有这个情况？能否把声音取消呢，声音确实挺大的。
> 
> 还有它睡眠会到一定时间自己醒吗？好像一个小时左右鼠标亮了😂

好像会有它自己唤醒的情况，不知道是不是系统偏好-节能里面开了电能小憩的原因。我把电能小憩关闭了，之后又没有这个问题我也没有注意。还有一个就是好像只能睡眠不能休眠，我晚上把把电脑睡眠，早上按下电源键系统立刻点亮，应该是没有进入休眠吧。

**Comment by Tcloser** [comment]
> 哎，我已经不想折腾了。今天安装个office，然后系统就卡死了，之前我用磁盘工具创建镜像，也卡死一次。我已经想回Windows10了。

我之前一直是win10+ubuntu双系统，前几天把win出厂恢复了，固态割了50g装mac系统，现在基本不用win了，mac装固态没卡过还，挺顺手

**Comment by Tcloser** [comment]
> > > > WOW, it's wonderful!!
> > > 
> > > 
> > > 我也有一个问题，就是开机的时候会有一个开机的声音，请问你有没有这个情况？能否把声音取消呢，声音确实挺大的。
> > 
> > 
> > 还有它睡眠会到一定时间自己醒吗？好像一个小时左右鼠标亮了😂
> 
> 好像会有它自己唤醒的情况，不知道是不是系统偏好-节能里面开了电能小憩的原因。我把电能小憩关闭了，之后有没有这个问题我也没有注意。还有一个就是好像只能睡眠不能休眠，我晚上把电脑睡眠，早上按下电源键系统立刻点亮，应该是没有进入休眠吧。

应该是·小憩·这个问题，问题不大，晚上关机好了，主要是白天唤醒能快一点。你的还带着光驱吗？我的拆了换了个固态

**Comment by ikarr** [comment]
光驱位我也换成硬盘了。我的固态是四年前买的三星750EVO，不知道是不是用的时间久了，mac系统下往系统盘写数据太多就容易把系统卡死。就比如今天安装office，安装大概会写7、8G数据，系统就卡的动不了。

**Comment by Tcloser** [comment]
我看网上说三星的不太适合做系统盘？ 我之前装office没出现过卡死问题。
我系统就预留了50g所以卸载了office装的wps，其他软件都放到机械盘里了。

**Comment by ikarr** [comment]
> 我看网上说三星的不太适合做系统盘？ 我之前装office没出现过卡死问题。
> 我系统就预留了50g所以卸载了office装的wps，其他软件都放到机械盘里了。

我好像找到原因了，好像是因为我装mac的硬盘装在光驱位导致的。把mac系统盘换到硬盘位，再测试数据写入，系统不会再卡死了。可能是光驱位的接口数据传输不稳定或者光驱硬盘托架有问题吧。能否加个QQ方便交流，我的QQ：583665989 😁
