### ISSUE TITLE
hdmi outputs 4k signal 

### ISSUE THREAD

**Issue by Ian-Shu** [Am1nCmd/Dell-Inspiron-14-7447-Pandora-Hackintosh#13]
I used the clover on 10.15.3 and found that my 4k display could not be recognized. I want to know if your clover can successfully drive a 4k display, thanks for your answer

**Comment by Am1nCmd** [comment]
I’m not sure about that. But you can use RDM. It really easy and support a lot of screen size

Sent from my iPhone

On 31 Jul 2020, at 7.19 PM, ian shu <notifications@github.com> wrote:

﻿

I used the clover on 10.15.3 and found that my 4k display could not be recognized. I want to know if your clover can successfully drive a 4k display, thanks for your answer
