### ISSUE TITLE
hope to update to support Mac OS 11

### ISSUE THREAD

**Issue by walle0207** [Am1nCmd/Dell-Inspiron-14-7447-Pandora-Hackintosh#18]
hope to update to support Mac OS 11

**Comment by Am1nCmd** [comment]
I'm not sure, since I won't update to macOS 11.x, as of right now, macOS 11 slow down mac performance,

**Comment by rahills** [comment]
If you're interested you can use my efi folder to boot big sur: https://github.com/rahills/Dell-Inspiron-7447-Pandora-Hackintosh-macOS-Big-Sur-with-OpenCore

**Comment by walle0207** [comment]
Thx a lot ,but my laptop hardware is not like yours ，it’s 4720HQ ，950 &nbsp;and so on ，it is stable for my LP？




------------------ Original ------------------
From: Riazul Islam Rahil ***@***.***&gt;
Date: 周日,5月 23,2021 01:30
To: Am1nCmd/Dell-Inspiron-14-7447-Pandora-Hackintosh ***@***.***&gt;
Cc: walle0207 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Am1nCmd/Dell-Inspiron-14-7447-Pandora-Hackintosh] hope to update to support Mac OS 11 (#18)





 
If you're interested you can use my efi folder to boot big sur: https://github.com/rahills/Dell-Inspiron-7447-Pandora-Hackintosh-macOS-Big-Sur-with-OpenCore

**Comment by Am1nCmd** [comment]
Actually I have a Open Core too. Booth (clover and open core) running well on bigsur.

Bigsur is not my mainly use OS. but yeah, its still compatible if you want. I’ll update it when I have free time

Sent from my iPhone

On 23 May 2021, at 6.46 AM, walle0207 ***@***.***> wrote:

﻿

Thx a lot ,but my laptop hardware is not like yours ，it’s 4720HQ ，950 &nbsp;and so on ，it is stable for my LP？




------------------ Original ------------------
From: Riazul Islam Rahil ***@***.***&gt;
Date: 周日,5月 23,2021 01:30
To: Am1nCmd/Dell-Inspiron-14-7447-Pandora-Hackintosh ***@***.***&gt;
Cc: walle0207 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Am1nCmd/Dell-Inspiron-14-7447-Pandora-Hackintosh] hope to update to support Mac OS 11 (#18)






If you're interested you can use my efi folder to boot big sur: https://github.com/rahills/Dell-Inspiron-7447-Pandora-Hackintosh-macOS-Big-Sur-with-OpenCore
