### ISSUE TITLE
I have a little problem and need your help, thank you.

### ISSUE THREAD

**Issue by Leslie-Luo** [Am1nCmd/Dell-Inspiron-14-7447-Pandora-Hackintosh#2]
Hello, my notebook is also Dell 7447. 
I can boot the system with your EFI file, but since my WIFI module has been replaced, I can't boot the system if I join the new Kexts.

**Comment by Leslie-Luo** [comment]
The new Kexts are BrcmFirmwareRepo and BrcmPatchRAM2

**Comment by Am1nCmd** [comment]
sorry for late reply, check out here https://github.com/RehabMan/OS-X-BrcmPatchRAM
