### ISSUE TITLE
Automatically reboot at apple logo loading screen

### ISSUE THREAD

**Issue by AnhToof** [Am1nCmd/Dell-Inspiron-14-7447-Pandora-Hackintosh#20]
I made a usb installer from guilde: https://dortania.github.io/OpenCore-Install-Guide/installer-guide/winblows-install.html#making-the-installer
The EFI folder is from this source. I met the issue above, It just load about 5 percent then reboot. Any idea about this?

**Comment by Am1nCmd** [comment]
Hi, not sure what is your issue.

I can't help without any detail
if you have already made the installer, just replace the EFI folder.

make sure your spec is the same as mine, otherwise, there need some other configs

**Comment by AnhToof** [comment]
Ok tkx, I should config from scratch
