### ISSUE TITLE
DSDT.dsl

### ISSUE THREAD

**Issue by aod321** [Am1nCmd/Dell-Inspiron-14-7447-Pandora-Hackintosh#3]
Hi,
Would you mind sharing the DSDT.dsl?The aml file is not so convenient to modify.
Thanks for your great work.

**Comment by Am1nCmd** [comment]
available on my github, that is my latest modified

On 23 Jan 2019, at 11.15, YinZi <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
Would you mind sharing the DSDT.dsl?The aml file is not so convenient to modify.
Thanks for your great work.
