### ISSUE TITLE
please

### ISSUE THREAD

**Issue by tzm0116** [Am1nCmd/Dell-Inspiron-14-7447-Pandora-Hackintosh#4]
replace it directly?

**Comment by Am1nCmd** [comment]
Yeah u can use my config. Replace your EFI with mine

**Comment by tzm0116** [comment]
emmmm,After replacement, the usb power supply is insufficient.What are the operations that need to be done after the replacement?
Many thanks！！

**Comment by Am1nCmd** [comment]
Ah I forgot about that, I’ll update tomorrow

That just need to be change the value.


On Apr 17, 2019 at 8:07 AM, <tzm0116<mailto:notifications@github.com>> wrote:


emmmm,After replacement, the usb power supply is insufficient.What are the operations that need to be done after the replacement?
Many thanks！！

**Comment by Am1nCmd** [comment]
I totally forgot about this
IOUSBHostFamily.kext


download and save to S/L/E that will fix your problem

**Comment by tzm0116** [comment]
very thx
