### ISSUE TITLE
Instruction

### ISSUE THREAD

**Issue by developerscontinusys** [Am1nCmd/Dell-Inspiron-14-7447-Pandora-Hackintosh#6]
Will you please provide a instruction on how to properly install it?

**Comment by Am1nCmd** [comment]
theres a lot of tutorial on forum, you can find one, then you can use my configuration

**Comment by AnhLT-Nexle** [comment]
@Am1nCmd Sorry for bothering you. I'm newbie so can you give me a keyword for the instruction or the forum that you said above? Thank in advanced

**Comment by Am1nCmd** [comment]
https://dortania.github.io/OpenCore-Install-Guide/
