### ISSUE TITLE
Is trackpad gestures working ?

### ISSUE THREAD

**Issue by zicaros** [Am1nCmd/Dell-Inspiron-14-7447-Pandora-Hackintosh#8]
I already clone your config almost function is working fine except trackpad guestures

pls help :(

**Comment by Am1nCmd** [comment]
not at all, only some gesture working, like scrool up and down, that is basically used

**Comment by darwinwu13** [comment]
@Am1nCmd can it work with vodooi2c ?

**Comment by Am1nCmd** [comment]
Im not sure. You can try


On Nov 20, 2019 at 7:47 PM, <Darwin<mailto:notifications@github.com>> wrote:


@Am1nCmd<https://github.com/Am1nCmd> can it work with vodooi2c ?

**Comment by Am1nCmd** [comment]
Two finger for scroll working fine on me. That is most used gesture


On Nov 20, 2019 at 7:47 PM, <Darwin<mailto:notifications@github.com>> wrote:


@Am1nCmd<https://github.com/Am1nCmd> can it work with vodooi2c ?
