### ISSUE TITLE
Hope to support Mac OS Catalina 10.15.1

### ISSUE THREAD

**Issue by sellcet** [Am1nCmd/Dell-Inspiron-14-7447-Pandora-Hackintosh#9]
Thank you for your contribution to this project. I used this clover on 10.15.1. Sometimes there will be a problem with the progress bar staying on the progress bar. I hope that I can get an EFI for 10.15, thank you very much!

**Comment by Am1nCmd** [comment]
yeah, my EFI work on 10.15.x too, but I'm not sure if there fully working,

since I'm stay on 10.14.6, a lot of my program still using 32bit and Catalina can't support 32bit, so I'll stay

**Comment by sellcet** [comment]
Thank you bro, I will wait for your latest progress. Good luck！

**Comment by e71828** [comment]
Sleep and Wake with Close and Open LID, **not work**. 
I have just found on Catalina 10.15.3.

**Comment by Am1nCmd** [comment]
> Sleep and Wake with Close and Open LID, **not work**.
> I have just found on Catalina 10.15.3.

I'm not tested it on 10.15.3

**Comment by standfv** [comment]
Hope to support Mac OS Catalina 10.15.6 please!

**Comment by walle0207** [comment]
IT WORKED NOW
